AfWindows
christianrauch/camera_ros pull request #14
Opened 2023-10-28 09:33 UTC by Woojin-Crive

#13

2023-10-28 11:05 UTC, christianrauch requested changes
As far as I can tell, this PR does not fix the original problem. It is just ignoring a setting. Additionally, it is not well documented in the commit message what is actually happening and why these changes are required.

2023-10-28 11:05 UTC, christianrauch commented on src/CameraNode.cpp
> +  pub_ci = this->create_publisher<sensor_msgs::msg::CameraInfo>("~/camera_info", 1, pub_options);
Why are you changing the default QoS settings? If you need to change the QoS settings, you can also do this via parameters. See `qos_overrides` in the full list of parameters: `ros2 param list`.

2023-10-28 11:05 UTC, christianrauch commented on CMakeLists.txt
> +
I would prefer not to add a launch file in this repo since the node already uses sensible defaults provided by libcamera.

2023-10-28 11:05 UTC, christianrauch commented on launch/camera_launch.py
> +            DeclareLaunchArgument("height", default_value="720", description="Camera image height"),
These defaults may not work for every camera.

2023-10-28 11:05 UTC, christianrauch commented on launch/camera_launch.py
> +            # You can add additional nodes or actions here as needed.
Most of these comments are redundant as they apply to generic launch file configurations, which are already documented in the official documentation.

2023-10-29 15:46 UTC, Woojin-Crive commented
Oh sorry for the dirty code.
I was just testing for private use.

2023-10-29 18:29 UTC, christianrauch commented
You seem to add unrelated commits to this PR. Are you intending to address your issue with the `AfWindows` control in this PR?

2023-10-29 19:26 UTC, closed without merging